# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'you_sure.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AreYouSure(object):
    def setupUi(self, AreYouSure):
        AreYouSure.setObjectName("AreYouSure")
        AreYouSure.resize(478, 159)
        self.buttonBox = QtWidgets.QDialogButtonBox(AreYouSure)
        self.buttonBox.setGeometry(QtCore.QRect(10, 120, 461, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(AreYouSure)
        self.label.setGeometry(QtCore.QRect(10, 15, 461, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(AreYouSure)
        self.buttonBox.accepted.connect(AreYouSure.accept)
        self.buttonBox.rejected.connect(AreYouSure.reject)
        QtCore.QMetaObject.connectSlotsByName(AreYouSure)

    def retranslateUi(self, AreYouSure):
        _translate = QtCore.QCoreApplication.translate
        AreYouSure.setWindowTitle(_translate("AreYouSure", "Dialog"))
        self.label.setText(_translate("AreYouSure", "Are you sure? \n"
"You can\'t cancel this action late."))
